import { useQuery } from "@tanstack/react-query";
import { useParams } from "react-router-dom";
import { api } from "../api/client";
import { DiagnosticRoute } from "../components/DiagnosticRoute";
import { DNSResult } from "../components/DNSResult";
import { HTTPResult } from "../components/HTTPResult";
import { PingResult } from "../components/PingResult";
import { StatusBadge } from "../components/StatusBadge";
import { TCPResult } from "../components/TCPResult";
import { TLSResult } from "../components/TLSResult";
import { TracerouteResult } from "../components/TracerouteResult";

export function PublicReportPage() {
  const { token = "" } = useParams();
  const report = useQuery({
    queryKey: ["public-report", token],
    queryFn: () => api.publicReport(token),
    enabled: Boolean(token),
    retry: false,
  });

  if (report.isLoading) {
    return (
      <main className="public-report-state">
        <span className="brand">
          NETSCOPE<span aria-hidden="true">/</span>
        </span>
        <p>Opening published evidence…</p>
      </main>
    );
  }
  if (report.error || !report.data) {
    return (
      <main className="public-report-state">
        <span className="brand">
          NETSCOPE<span aria-hidden="true">/</span>
        </span>
        <h1>Public report unavailable</h1>
        <p>
          This link is invalid, expired, or has been revoked by its workspace.
        </p>
      </main>
    );
  }

  const { run } = report.data;
  const result = (type: string) =>
    run.results.find((item) => item.type === type);
  const dns = result("dns");
  const tcp = result("tcp");
  const http = result("http");
  const tls = result("tls");
  const ping = result("ping");
  const traceroute = result("traceroute");

  return (
    <div className="public-report-shell">
      <header className="public-report-header">
        <span className="brand">
          NETSCOPE<span aria-hidden="true">/</span>
        </span>
        <div>
          <span>Published evidence</span>
          <strong>{report.data.workspaceName}</strong>
        </div>
      </header>
      <main className="public-report">
        <section className="public-report-title">
          <div>
            <p className="section-label">
              REPORT / {run.id.slice(0, 8)} / READ ONLY
            </p>
            <h1>{run.normalizedHost}</h1>
            <code>{run.target}</code>
          </div>
          <StatusBadge status={run.status} />
        </section>

        <dl className="public-report-facts">
          <div>
            <dt>Workspace</dt>
            <dd>{report.data.workspaceName}</dd>
          </div>
          <div>
            <dt>Run created</dt>
            <dd>{new Date(run.createdAt).toLocaleString()}</dd>
          </div>
          <div>
            <dt>Published</dt>
            <dd>{new Date(report.data.publishedAt).toLocaleString()}</dd>
          </div>
          <div>
            <dt>Link expires</dt>
            <dd>{new Date(report.data.expiresAt).toLocaleString()}</dd>
          </div>
        </dl>

        <DiagnosticRoute run={run} />

        <section className="public-result-ledger">
          <div className="ledger-heading">
            <p className="section-label">
              TECHNICAL RECORD / PERSISTED EVIDENCE
            </p>
            <h2>Diagnostic results</h2>
            <p>
              Structured probe evidence published from a NetScope workspace.
            </p>
          </div>
          {dns && <DNSResult result={dns} />}
          {ping && <PingResult result={ping} />}
          {traceroute && <TracerouteResult result={traceroute} />}
          {tcp && <TCPResult result={tcp} />}
          {tls && <TLSResult result={tls} />}
          {http && <HTTPResult result={http} />}
          {run.results.length === 0 && (
            <p className="empty-collaboration">
              This report contains no completed probe output.
            </p>
          )}
        </section>
      </main>
      <footer className="public-report-footer">
        <span>Generated by NetScope</span>
        <span>Read-only technical evidence</span>
      </footer>
    </div>
  );
}
